name: Node.js CI ShopDev By Le Trung Hau

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: BE_ShopDEV/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: BE_ShopDEV

     - name: Build TypeScript project
      run: npm run build
      working-directory: ./BE_ShopDEV

    - name: Deploy application with PM2
      run: |
        pm2 delete shopdev-be || true
        pm2 start dist/index.js --name=shopdev-be
      working-directory: ./BE_ShopDEV
      
    - name: Save PM2 process list
      run: pm2 save
      working-directory: ./BE_ShopDEV
